CREATE TABLE email_verification_token
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code            VARCHAR(255) NOT NULL,
    email           VARCHAR(255) NOT NULL,
    user_id         INTEGER,
    created_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    expiration_time TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_email_verification_token PRIMARY KEY (id)
);

CREATE TABLE knowledge
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title          VARCHAR(255)     NOT NULL,
    content        TEXT,
    user_id        INTEGER,
    price          DOUBLE PRECISION NOT NULL,
    is_encrypted   BOOLEAN          NOT NULL,
    purchase_count INTEGER          NOT NULL,
    created_at     TIMESTAMP WITHOUT TIME ZONE,
    updated_at     TIMESTAMP WITHOUT TIME ZONE,
    status         VARCHAR(255),
    CONSTRAINT pk_knowledge PRIMARY KEY (id)
);

CREATE TABLE knowledge_purchase
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    knowledge_id     BIGINT  NOT NULL,
    user_id          INTEGER NOT NULL,
    payment_order_id BIGINT  NOT NULL,
    purchased_at     TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_knowledge_purchase PRIMARY KEY (id)
);

CREATE TABLE knowledge_tags
(
    knowledge_id BIGINT NOT NULL,
    tag          VARCHAR(255)
);

CREATE TABLE notification
(
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id         INTEGER,
    content         VARCHAR(255),
    is_read         BOOLEAN,
    created_at      TIMESTAMP WITHOUT TIME ZONE,
    expire_at       TIMESTAMP WITHOUT TIME ZONE,
    related_data_id INTEGER,
    CONSTRAINT pk_notification PRIMARY KEY (id)
);

CREATE TABLE password_reset_tokens
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token           VARCHAR(255) NOT NULL,
    user_id         INTEGER,
    expiration_time TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_password_reset_tokens PRIMARY KEY (id)
);

CREATE TABLE payment_order
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_no       VARCHAR(255),
    amount         DECIMAL,
    subject        VARCHAR(255),
    body           VARCHAR(255),
    pay_type       VARCHAR(255),
    status         VARCHAR(255),
    user_id        INTEGER,
    create_time    TIMESTAMP WITHOUT TIME ZONE,
    expire_time    TIMESTAMP WITHOUT TIME ZONE,
    transaction_id VARCHAR(255),
    pay_time       TIMESTAMP WITHOUT TIME ZONE,
    payload        TEXT,
    knowledge_id   BIGINT,
    CONSTRAINT pk_payment_order PRIMARY KEY (id)
);

CREATE TABLE sidedata
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    icon          VARCHAR(255),
    current       BOOLEAN     DEFAULT 0,
    href          VARCHAR(255),
    name          VARCHAR(255),
    created_at    TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    updated_at    TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    tiptap_json   JSON,
    user_id       INTEGER,
    expired_at    TIMESTAMP WITHOUT TIME ZONE,
    status        VARCHAR(20) DEFAULT 'PENDING',
    reject_reason TEXT,
    tag_id        INTEGER,
    CONSTRAINT pk_sidedata PRIMARY KEY (id)
);

CREATE TABLE tags
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255) NOT NULL,
    user_id    INTEGER      NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    version    INTEGER,
    CONSTRAINT pk_tags PRIMARY KEY (id)
);

CREATE TABLE "user"
(
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    password_hash   VARCHAR(60)               NOT NULL,
    username        VARCHAR(100),
    role            VARCHAR(20) DEFAULT '1',
    email           VARCHAR(255),
    created_at      TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    updated_at      TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    email_verified  BOOLEAN     DEFAULT FALSE NOT NULL,
    vip_active      BOOLEAN,
    vip_expire_time TIMESTAMP WITHOUT TIME ZONE,
    balance         DECIMAL(10, 2)            NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id)
);

ALTER TABLE email_verification_token
    ADD CONSTRAINT uc_email_verification_token_user UNIQUE (user_id);

ALTER TABLE knowledge_purchase
    ADD CONSTRAINT uc_knowledge_purchase_payment_order UNIQUE (payment_order_id);

ALTER TABLE password_reset_tokens
    ADD CONSTRAINT uc_password_reset_tokens_token UNIQUE (token);

ALTER TABLE password_reset_tokens
    ADD CONSTRAINT uc_password_reset_tokens_user UNIQUE (user_id);

ALTER TABLE payment_order
    ADD CONSTRAINT uc_payment_order_orderno UNIQUE (order_no);

ALTER TABLE "user"
    ADD CONSTRAINT uc_user_email UNIQUE (email);

CREATE INDEX idx_created_at ON sidedata (created_at);

CREATE INDEX idx_status ON sidedata (status);

CREATE INDEX idx_status_created_at ON sidedata (status, created_at DESC);

ALTER TABLE email_verification_token
    ADD CONSTRAINT FK_EMAIL_VERIFICATION_TOKEN_ON_USER FOREIGN KEY (user_id) REFERENCES "user" (id);

ALTER TABLE knowledge
    ADD CONSTRAINT FK_KNOWLEDGE_ON_USER FOREIGN KEY (user_id) REFERENCES "user" (id);

ALTER TABLE knowledge_purchase
    ADD CONSTRAINT FK_KNOWLEDGE_PURCHASE_ON_KNOWLEDGE FOREIGN KEY (knowledge_id) REFERENCES knowledge (id);

ALTER TABLE knowledge_purchase
    ADD CONSTRAINT FK_KNOWLEDGE_PURCHASE_ON_PAYMENT_ORDER FOREIGN KEY (payment_order_id) REFERENCES payment_order (id);

ALTER TABLE knowledge_purchase
    ADD CONSTRAINT FK_KNOWLEDGE_PURCHASE_ON_USER FOREIGN KEY (user_id) REFERENCES "user" (id);

ALTER TABLE notification
    ADD CONSTRAINT FK_NOTIFICATION_ON_USER FOREIGN KEY (user_id) REFERENCES "user" (id);

ALTER TABLE password_reset_tokens
    ADD CONSTRAINT FK_PASSWORD_RESET_TOKENS_ON_USER FOREIGN KEY (user_id) REFERENCES "user" (id);

ALTER TABLE payment_order
    ADD CONSTRAINT FK_PAYMENT_ORDER_ON_KNOWLEDGE FOREIGN KEY (knowledge_id) REFERENCES knowledge (id);

ALTER TABLE payment_order
    ADD CONSTRAINT FK_PAYMENT_ORDER_ON_USER FOREIGN KEY (user_id) REFERENCES "user" (id);

ALTER TABLE sidedata
    ADD CONSTRAINT FK_SIDEDATA_ON_TAG FOREIGN KEY (tag_id) REFERENCES tags (id);

ALTER TABLE sidedata
    ADD CONSTRAINT FK_SIDEDATA_ON_USER FOREIGN KEY (user_id) REFERENCES "user" (id);

ALTER TABLE tags
    ADD CONSTRAINT FK_TAGS_ON_USER FOREIGN KEY (user_id) REFERENCES "user" (id);

ALTER TABLE knowledge_tags
    ADD CONSTRAINT fk_knowledge_tags_on_knowledge FOREIGN KEY (knowledge_id) REFERENCES knowledge (id);
