spring:
  mail:
    host: smtp.qq.com
    port: 465
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    protocol: smtps
    properties:
      mail.smtp.ssl.enable: true
      mail.smtp.auth: true
      mail.smtp.timeout: 5000





