spring:
  profiles:
    active: dev  # 默认开发环境
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
    hibernate:
      ddl-auto: validate
    show-sql: true
  jackson:
    time-zone: UTC
    serialization:
      write-dates-as-timestamps: false
  application:
    name: backend
  flyway:
    baseline-on-migrate: true
    # 引入配置
  config:
    import:
      - classpath:application-mail.yml
      - classpath:application-payment.yml

app:
  is-production: true
# JWT 配置
jwt:
  secret: EcA5J8veaW92g4GY5o3hBerZ5DxsGar/fKRAe/WKilI=
  expiration: 86400000
server:
  address: 0.0.0.0

