spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pkmsystem?serverTimezone=UTC
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:higashi}
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration/mysql  # 指向 MySQL 脚本目录